apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-account-shredder
  labels:
    name: aws-account-shredder
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-account-shredder
  template:
    metadata:
      labels:
        name: aws-account-shredder
    spec:
      serviceAccountName: aws-account-shredder
      containers:
        - name: aws-account-shredder
          image: quay.io/agautam/aws-account-shredder:v137
          env:
            - name : OPERATOR_NAME
              value: "aws-account-shredder"